AWSTemplateFormatVersion: 2010-09-09
Description: Creation of codepipeline  
Parameters:  
  BucketNameParameter:
    Type: String
    Description: S3 Bucket Name
  GitHubOAuthToken:
    Type: String
    NoEcho: true
    MinLength: 40
    MaxLength: 40
    AllowedPattern: "^[A-Za-z][a-zA-Z0-9@%$_-]{12,}$"
  GitHubOwner:
    Type: String
    Default: Harish9395
    AllowedPattern: "[A-Za-z0-9-]+"
  GitHubRepo: 
    Type: String
    Default: github-codepipeline 
    AllowedPattern: "[A-Za-z0-9-]+" 
  GitHubBranch:
    Type: String
    Default: master
    AllowedPattern: "[A-Za-z0-9-]+" 
  ApplicationStackName:
    Type: String
    Default: github-codepipeline-app
    AllowedPattern: "[A-Za-z0-9-]+"
Resources: 
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketNameParameter
    DeletionPolicy: Delete
  Mypipeline: 
    Type: AWS::CodePipeline::Pipeline 
    Properties:  
      RoleArn: !GetAtt CodePipelineRole.Arn 
      ArtifactStore: 
        Location: !Ref BucketNameParameter
        Type: S3 
      RestartExecutionOnUpdate: true
      Stages: 
      - Name: Source 
        Actions: 
        - Name: SourceAction 
          InputArtifacts: [] 
          ActionTypeId:  
            Category: Source 
            Owner: ThirdParty 
            Version: 1 
            Provider: GitHub 
          OutputArtifacts: 
          - Name: SourceCode 
          Configuration: 
            Owner: !Ref GitHubOwner
            Repo: !Ref GitHubRepo 
            Branch: !Ref GitHubBranch 
            PollForSourceChanges: true 
            OAuthToken: !Ref GitHubOAuthToken
          RunOrder: 1 
      - Name: Deploy 
        Actions: 
        - Name: CloudFormationDeploy 
          ActionTypeId:
            Category: Deploy
            Owner: AWS
            Provider: CloudFormation
            Version: '1' 
          InputArtifacts:
            - Name: SourceCode 
          Configuration:
            ActionMode: CREATE_UPDATE
            Capabilities: CAPABILITY_IAM
            RoleArn: !GetAtt CloudformationRole.Arn
            StackName: !Ref ApplicationStackName
            TemplatePath: !Sub "SourceCode::application.yaml"
          RunOrder: 1 
  CodePipelineRole:
    Type: AWS::IAM::Role 
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: codepipeline.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns: 
      - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess
      - arn:aws:iam::aws:policy/AmazonS3FullAccess
  CloudformationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          Effect: Allow
          Principal:
            Service: cloudformation.amazonaws.com
          Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess 
        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess 
        - arn:aws:iam::aws:policy/AWSCodePipelineFullAccess

